replicaCount: 1

image:
  repository: europe-west2-docker.pkg.dev/public-endpoint-monitor/public-endpoint-monitor-registry/public-endpoint-monitor
  tag: latest
  pullPolicy: IfNotPresent

probe:
  url: https://www.google.com
  interval: 30   # seconds

service:
  type: ClusterIP
  port: 9000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

scrape:
  interval: 30s
