apiVersion: v1
kind: Service
metadata:
  name: {{ include "pem.fullname" . }}-metrics
  labels: {{- include "pem.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "pem.selectorLabels" . | nindent 6 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
